### ISSUE TITLE
Request for additional features

### ISSUE THREAD

**Issue by RexWzh** [JuliaML/OpenAI.jl#34]
Hello, @rory-linehan  . Your package is excellent, providing handy tools for calling OpenAI APIs, text-embeddings, image-related functionalities, etc. (not sure if speech-related features will be considered).
I'm Rex, and I'm maintaining a chat-like Julia package called [ChatAPICall](https://github.com/RexWzh/ChatAPICall.jl), which, as mentioned [here](https://github.com/JuliaRegistries/General/pull/80319#issuecomment-1486973894), focuses more on chat-specific features to build tools upon.

I have created a Python tool called [openai_api_call](https://github.com/RexWzh/openai_api_call) that shares similarities with OpenAI.jl. I am interested in contributing some of its features to OpenAI.jl and using it as a dependency. Specifically, I would like to include the following features:

- `getapiusage` function to retrieve API usage information
- Initialization of the `api_key` from the default environment (see https://github.com/JuliaML/OpenAI.jl/pull/35)
- Allowance of `timeout`, `interval`, and `retries` parameters in requests to set access timeout, interval, and retry count.

If needed, I can also help to update the documentation, reorganize code files, and perform other tasks as necessary. Thank you for your reading ;)

**Comment by algunion** [comment]
Hey, @RexWzh, this is a community package started by @rory-linehan - my contribution was primarily related to things I wanted to see in the package and were missing at the time.

You are welcome to extend it, add new features, and improve the documentation.

**Comment by rory-linehan** [comment]
Welcome, and feel free to open PRs. Though the third bullet point might already have been implemented by @algunion , if I understand correctly: https://github.com/JuliaML/OpenAI.jl/pull/31

**Comment by algunion** [comment]
> Welcome, and feel free to open PRs. Though the third bullet point might already have been implemented by @algunion , if I understand correctly: #31

You are right; all the [HTTP.jl keyword arguments](https://juliaweb.github.io/HTTP.jl/stable/client/#Keyword-Arguments) can be passed as NamedTuple using `http_kwargs` (this is also shown in the documentation).

**Comment by rory-linehan** [comment]
I think this release addresses everything: https://github.com/JuliaML/OpenAI.jl/releases/tag/v0.8.4
