### ISSUE TITLE
Hope  expose the base_url by setting the OPENAI_API_BASE environment variable.

### ISSUE THREAD

**Issue by zsz00** [JuliaML/OpenAI.jl#37]

**Comment by zsz00** [comment]
@rory-linehan

**Comment by rory-linehan** [comment]
Can you open a PR with an example of what you're trying to solve?

**Comment by zsz00** [comment]
![image](https://github.com/JuliaML/OpenAI.jl/assets/12711073/b56244c6-607c-47a4-ba39-6ea97e555cb9)

api.openai.com is not directly accessible in China, need to use the proxied api address. base_url  need change, but now it's hardcoded here.

**Comment by rory-linehan** [comment]
This is a good idea, I'll have this fixed by the end of the weekend.

**Comment by rory-linehan** [comment]
After looking at this, I'm wondering why you can't do the following in your code after adding some environment variable like `OPENAI_BASE_URL_OVERRIDE` on your side

```julia
using OpenAI
provider = OpenAI.OpenAIProvider(
    api_key=ENV["OPENAI_API_KEY"],
    base_url=ENV["OPENAI_BASE_URL_OVERRIDE"]
)
response = create_chat(
    provider,
    "gpt-3.5-turbo",
    [Dict("role" => "user", "content" => "Write some ancient Greek poetry")]
)
```
Overriding the default value seems like the way to go.

**Comment by zsz00** [comment]
this is ok, ths.

**Comment by likanzhan** [comment]
@zsz00 
Sorry to opt in.
I'm wondering what the  `proxied api address` alike?
I have no experience in setting up this.
Thanks.

**Comment by zsz00** [comment]
https:openai.api2d.net/v1
