### ISSUE TITLE
Impact of potential breaking changes

### ISSUE THREAD

**Issue by algunion** [JuliaML/OpenAI.jl#41]
The `streamcallback` is called with the raw string chunk at the moment - which is pretty useless as it is, and everybody needs to parse it so they can actually extract the `content` from the chunk.

However, we already have that parser in place - but we only use that to generate a proper `Vector{JSON3.Object}` response (once the streaming is completed).

My suggestion is to call the `streamcallback` either using a JSON3 object or a Dict (the ordering doesn't matter). The allocation issue also doesn't really matter here (the real bottleneck will always be OpenAI API) - so I would argue that ergonomics is more important in the context.

This change would be a breaking change for everybody using the package with the `streamcallback` option.

@rory-linehan, what is the long-term vision for this package, and how are these decisions made? 

I am asking because I am pretty invested in having a reliable OpenAI API - and I want to understand if pushing the work I already did can bring value to this package.

**Comment by rory-linehan** [comment]
> what is the long-term vision for this package

The only long term vision I had for this package was to approach feature parity over time with OpenAI's [Python package](https://github.com/openai/openai-python). 

> how are these decisions made?

Until someone articulates a compelling reason to change, I think these decisions should be made case-by-case with technical justifications. Personally, I favor a more laissez-faire approach to changes like this while the package is relatively small. This will allow us room to maneuver and create the highest quality package.

> so I would argue that ergonomics is more important in the context.

Completely agree.

> This change would be a breaking change for everybody using the package with the streamcallback option.

I think this is probably fine, as long as we document the breaking change. Semver will take care of the rest.
