### ISSUE TITLE
Docs are not being deployed

### ISSUE THREAD

**Issue by jotas6** [JuliaML/OpenAI.jl#43]
Hi! I am unsure about how to solve this problem, so I am opening an issue in case someone has a better idea of how to fix it.

I noticed the last release didn't produce any changes in the documentation (https://juliaml.github.io/OpenAI.jl/dev/) when it should have (there were two changes, made in #38 and #39). Looking at the GitHub actions log, it seems like it was some error related to the repository URL:

![image](https://github.com/JuliaML/OpenAI.jl/assets/80299581/44e9948a-8991-4137-a50f-32649b60a174)

I was thinking that maybe setting `repo` to something like `"github.com/JuliaML/OpenAI.jl.git"` here https://github.com/JuliaML/OpenAI.jl/blob/2cfe791e0e4e21fd4ed9089d2a5e19ad359cf73a/docs/make.jl#L6 might solve the issue, but I am not very experienced with `Documenter.jl` and I don't really know how I could test if this solution would work.

**Comment by rory-linehan** [comment]
Hmm, thanks for bringing this up. We transferred the repo recently from my personal to the JuliaML org and looks like that broke the docs build. I'll fix it this weekend
