### ISSUE TITLE
Not possible to create a post request with more than 268 strings for create_embeddings()?

### ISSUE THREAD

**Issue by atantos** [JuliaML/OpenAI.jl#48]
Hi there.

It seems there is a time or string limit for doing post requests? Although I am able to do a one time request for 1000 strings out of the overview column in R, I cannot do more than 268 right now. Is it an issue with the package or am I missing something?

Thanks!

```
using CSV, DataFrames, OpenAI
horror_movies = CSV.read(Downloads.download("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-11-01/horror_movies.csv"), DataFrame);

r = create_embeddings(
        ENV["OPENAI_API_KEY"],
        horror_movies.overview[1:268]
    )
```

**Comment by atantos** [comment]
I missed the model as the second argument. My bad!

**Comment by algunion** [comment]
Please see the answer [here](https://discourse.julialang.org/t/not-possible-to-create-a-post-request-with-more-than-268-strings-for-create-embeddings-of-openai-jl/102985/2?u=algunion).

**Comment by cpfiffer** [comment]
Closing as this is resolved in the discourse post linked above.
