### ISSUE TITLE
Allow change base_url

### ISSUE THREAD

**Issue by rcherukuri12** [JuliaML/OpenAI.jl#51]
allow base_url to be set ...just not that but all other OpenAI config params.
This would make it flexible to switch and work as client for non-OpenAI local LLM servers that support OpenAI interface(s).

Adding more details:
I have a local LLM server LiteLLM running that honors OpenAPI calls.
I had to find out a round-about way of doing things like:
o = OpenAI.OpenAIProvider("junk", "http://localhost:8000", "")
and then passing this to the second create_chat(...) method to make it work.
would be great if the API is a bit more cleaner.

**Comment by rory-linehan** [comment]
Yes, this is a good idea - there's [another issue](https://github.com/JuliaML/OpenAI.jl/issues/37#issuecomment-1797864833) with the same idea.

By cleaner API, are you referring to the `base_url` problem, or something more general?

**Comment by rcherukuri12** [comment]
Thank you, my comment on the cleaner api just meant that the Azure Provider ( it doesn't have to be part of the main src, but can be provided as an example of override ).

**Comment by rory-linehan** [comment]
That seems like a reasonable refactor

**Comment by rcherukuri12** [comment]
Here is the example code for a local LLM that I run using OpenAI.jl :

https://github.com/rcherukuri12/ollama_julia_code_generator/blob/main/LiteLLM_Ollama_client.jl

**Comment by cpfiffer** [comment]
Sorry to revive a dead issue -- was there a good way to set the OpenAI organization key for requests?

**Comment by rory-linehan** [comment]
There isn't a canonical way implemented, I think
